package com.example.sprintboot_test.utils;

import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;

public class getAll17002 {
//    public static void main(String[] args) {
//        JSONObject parse = (JSONObject)JSONObject.parse("{\n" +
//                "  \"code\": 200,\n" +
//                "  \"message\": null,\n" +
//                "  \"data\": [\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"8ca2efb4a5f18d7900ac511fbcdfae2a\",\n" +
//                "      \"alarmId\": 2,\n" +
//                "      \"alarmLevel\": 5,\n" +
//                "      \"alarmStatus\": 2,\n" +
//                "      \"alarmAlias\": \"固定高高报\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"炼油部\",\n" +
//                "      \"factoryName\": \"炼油部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"渣油加氢装置\",\n" +
//                "      \"unitName\": \"6#炼油渣油加氢装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"渣油加氢K1102\",\n" +
//                "      \"equipmentNo\": \"K1102\",\n" +
//                "      \"graphType\": 25,\n" +
//                "      \"equipmentName\": \"渣油加氢K1102\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200830139\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": 3000,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1666239484429\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"068ca4576ab0eeff855484ca6f0afd1f\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"芳烃部\",\n" +
//                "      \"factoryName\": \"芳烃部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"4#汽油加氢装置\",\n" +
//                "      \"unitName\": \"4#汽油加氢装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"循环氢压缩机C201\",\n" +
//                "      \"equipmentNo\": \"SHSHC201\",\n" +
//                "      \"graphType\": 25,\n" +
//                "      \"equipmentName\": \"循环氢压缩机GB-201\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200705174\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301711000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"076562e821efe96edd0d00f3f7da94d6\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"炼油部\",\n" +
//                "      \"factoryName\": \"炼油部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"2#焦化装置\",\n" +
//                "      \"unitName\": \"4#炼油2#延迟焦化装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"2#焦化富气压缩机K-9201\",\n" +
//                "      \"equipmentNo\": \"K9210\",\n" +
//                "      \"graphType\": 25,\n" +
//                "      \"equipmentName\": \"2#焦化富气压缩机K-9201\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200829158\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301762000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"1d1aeb0d2c930ba48da5471c4ddd8e30\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"芳烃部\",\n" +
//                "      \"factoryName\": \"芳烃部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"3#连续重整装置\",\n" +
//                "      \"unitName\": \"3#连续重整装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"K3202-3压缩机组\",\n" +
//                "      \"equipmentNo\": \"K32023\",\n" +
//                "      \"graphType\": 25,\n" +
//                "      \"equipmentName\": \"K3202-3压缩机组\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200700815\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301711000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"1df6a1609f639924811815e57230ba64\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"热电部\",\n" +
//                "      \"factoryName\": \"热电部\",\n" +
//                "      \"factorySort\": 6,\n" +
//                "      \"unitId\": \"汽机装置\",\n" +
//                "      \"unitName\": \"汽机装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"5#发电机组\",\n" +
//                "      \"equipmentNo\": \"5FDJZ\",\n" +
//                "      \"graphType\": 11,\n" +
//                "      \"equipmentName\": \"5#发电机组\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200889370\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301805000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"22aad6be42569376a76986e8f5972e5b\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"炼油部\",\n" +
//                "      \"factoryName\": \"炼油部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"3#柴油加氢装置\",\n" +
//                "      \"unitName\": \"1#炼油3#柴油加氢装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"循环氢压缩机K-2102\",\n" +
//                "      \"equipmentNo\": \"K2102\",\n" +
//                "      \"graphType\": 25,\n" +
//                "      \"equipmentName\": \"循环氢压缩机K-2102\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200790160\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301762000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"39f5fc2a2a12fe3052cbe52e50588f0e\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"炼油部\",\n" +
//                "      \"factoryName\": \"炼油部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"2#炼油烷基化装置\",\n" +
//                "      \"unitName\": \"2#炼油烷基化装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"200824042637404\",\n" +
//                "      \"equipmentNo\": \"SHK7201\",\n" +
//                "      \"graphType\": 109,\n" +
//                "      \"equipmentName\": \"制冷压缩机K-7201\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"沈鼓\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301762000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"4022b7b2b98eabe3004a0f834718b7ae\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"芳烃部\",\n" +
//                "      \"factoryName\": \"芳烃部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"2#甲苯歧化异构化\",\n" +
//                "      \"unitName\": \"2#甲苯歧化异构化\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"K501压缩机组\",\n" +
//                "      \"equipmentNo\": \"SHSHK501\",\n" +
//                "      \"graphType\": 25,\n" +
//                "      \"equipmentName\": \"K501压缩机组\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200700235\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301711000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"4adc6ae8fa0191ee5e06287ebc437ced\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"芳烃部\",\n" +
//                "      \"factoryName\": \"芳烃部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"2#甲苯歧化异构化\",\n" +
//                "      \"unitName\": \"2#甲苯歧化异构化\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"K701压缩机组\",\n" +
//                "      \"equipmentNo\": \"SHSHK701\",\n" +
//                "      \"graphType\": 25,\n" +
//                "      \"equipmentName\": \"K701压缩机组\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200700301\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301711000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"4d890c3d2c98d834ecb4d16e4480d65e\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"芳烃部\",\n" +
//                "      \"factoryName\": \"芳烃部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"3#连续重整装置\",\n" +
//                "      \"unitName\": \"3#连续重整装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"K3202-1压缩机组\",\n" +
//                "      \"equipmentNo\": \"K320211\",\n" +
//                "      \"graphType\": 25,\n" +
//                "      \"equipmentName\": \"K3202-1压缩机组\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200700813\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301711000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"6bd14021cc84c22dfc410ae64cf63a1e\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"烯烃部\",\n" +
//                "      \"factoryName\": \"烯烃部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"2#烯烃装置\",\n" +
//                "      \"unitName\": \"2#乙烯装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"裂解气压缩机EGB-2201\",\n" +
//                "      \"equipmentNo\": \"EGB2201\",\n" +
//                "      \"graphType\": 15,\n" +
//                "      \"equipmentName\": \"裂解气压缩机EGB-2201\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200681832\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301813000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"766b3ed2cec6c5cdbfe53615b89e1a89\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"烯烃部\",\n" +
//                "      \"factoryName\": \"烯烃部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"2#烯烃装置\",\n" +
//                "      \"unitName\": \"2#乙烯装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"乙烯冷煤压缩机EGB-601\",\n" +
//                "      \"equipmentNo\": \"EGB601\",\n" +
//                "      \"graphType\": 25,\n" +
//                "      \"equipmentName\": \"乙烯冷媒压缩机EGB-601\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200681638\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301814000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"7eeb577f1b478a7ae7929559773c2f7b\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"炼油部\",\n" +
//                "      \"factoryName\": \"炼油部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"中压加氢裂化装置\",\n" +
//                "      \"unitName\": \"3#炼油中压加氢裂化装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"循环氢压缩机K/HK-6102\",\n" +
//                "      \"equipmentNo\": \"HK6102\",\n" +
//                "      \"graphType\": 25,\n" +
//                "      \"equipmentName\": \"循环氢压缩机K/HK-6102\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200821409\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301761000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"80bc3be8aff4aebd640d076abecfe555\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"芳烃部\",\n" +
//                "      \"factoryName\": \"芳烃部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"2#连续再生重整装置\",\n" +
//                "      \"unitName\": \"2#连续重整装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"K202-2压缩机组\",\n" +
//                "      \"equipmentNo\": \"K2022\",\n" +
//                "      \"graphType\": 34,\n" +
//                "      \"equipmentName\": \"K202-2压缩机组\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200700111\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301711000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"8278e169709408e86f54a6cc03a64c60\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"烯烃部\",\n" +
//                "      \"factoryName\": \"烯烃部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"2#烯烃装置\",\n" +
//                "      \"unitName\": \"2#乙烯装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"丙烯冷煤压缩机EGB-501\",\n" +
//                "      \"equipmentNo\": \"EGB501\",\n" +
//                "      \"graphType\": 25,\n" +
//                "      \"equipmentName\": \"丙烯冷媒压缩机EGB-501\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200681637\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301813000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"8929efb198453960346c48ed903b8947\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"炼油部\",\n" +
//                "      \"factoryName\": \"炼油部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"渣油加氢装置\",\n" +
//                "      \"unitName\": \"6#炼油渣油加氢装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"渣油加氢K1802\",\n" +
//                "      \"equipmentNo\": \"K1802\",\n" +
//                "      \"graphType\": 25,\n" +
//                "      \"equipmentName\": \"渣油加氢K1802\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200830149\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301761000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"8d3cf3263c14d5077aea6ff07a7365e7\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"芳烃部\",\n" +
//                "      \"factoryName\": \"芳烃部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"3#连续重整装置\",\n" +
//                "      \"unitName\": \"3#连续重整装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"K3202-2压缩机组\",\n" +
//                "      \"equipmentNo\": \"K32022\",\n" +
//                "      \"graphType\": 25,\n" +
//                "      \"equipmentName\": \"K3202-2压缩机组\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200700814\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301711000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"912fc3a4703bf6503ef10278a1b90370\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"芳烃部\",\n" +
//                "      \"factoryName\": \"芳烃部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"高压加氢裂化装置\",\n" +
//                "      \"unitName\": \"高压加氢裂化装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"循环氢压缩机GB-101\",\n" +
//                "      \"equipmentNo\": \"SHSHGB101\",\n" +
//                "      \"graphType\": 25,\n" +
//                "      \"equipmentName\": \"循环氢压缩机GB-101\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200699751\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301711000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"91a85d0d3f88f8864da941fcaed55964\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"炼油部\",\n" +
//                "      \"factoryName\": \"炼油部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"2#重油催化裂化装置\",\n" +
//                "      \"unitName\": \"5#炼油2#催化裂化装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"主风机K2101（AV90）\",\n" +
//                "      \"equipmentNo\": \"K2101AV90\",\n" +
//                "      \"graphType\": 7,\n" +
//                "      \"equipmentName\": \"主风机K2101（AV90）\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200843721\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301762000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"9ab3ee511bcaec77832a89ed1f681857\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"化工部\",\n" +
//                "      \"factoryName\": \"化工部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"1#乙二醇装置\",\n" +
//                "      \"unitName\": \"1#环氧乙烷/乙二醇装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"循环气压缩机2C-115\",\n" +
//                "      \"equipmentNo\": \"2C115\",\n" +
//                "      \"graphType\": 66,\n" +
//                "      \"equipmentName\": \"循环气压缩机2C-115\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200741404\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301752000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"a9810141e5c7d19a6cea0a29cc4cb451\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"塑料部\",\n" +
//                "      \"factoryName\": \"塑料部\",\n" +
//                "      \"factorySort\": 7,\n" +
//                "      \"unitId\": \"4PE装置\",\n" +
//                "      \"unitName\": \"4PE装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"循环气压缩机PK-401\",\n" +
//                "      \"equipmentNo\": \"PK401\",\n" +
//                "      \"graphType\": 25,\n" +
//                "      \"equipmentName\": \"循环气压缩机PK-401\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200814835\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301811000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"b68c5c3cd63fa9c0021ec30e6204ca4e\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"烯烃部\",\n" +
//                "      \"factoryName\": \"烯烃部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"2#烯烃装置\",\n" +
//                "      \"unitName\": \"2#乙烯装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"裂解气压缩机EGB-201\",\n" +
//                "      \"equipmentNo\": \"EGB201\",\n" +
//                "      \"graphType\": 15,\n" +
//                "      \"equipmentName\": \"裂解气压缩机EGB-201\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200681633\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301813000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"bc35fcc1066da8462c4cc9e63764ea54\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"芳烃部\",\n" +
//                "      \"factoryName\": \"芳烃部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"1#连续再生重整装置\",\n" +
//                "      \"unitName\": \"1#连续重整装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"循环氢压缩机GB-301\",\n" +
//                "      \"equipmentNo\": \"SHSHGB301\",\n" +
//                "      \"graphType\": 25,\n" +
//                "      \"equipmentName\": \"循环氢压缩机GB-301\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200699845\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301711000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"c3e6e6919f8bc6926090212ca2db2475\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"炼油部\",\n" +
//                "      \"factoryName\": \"炼油部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"1#焦化装置\",\n" +
//                "      \"unitName\": \"4#炼油1#延迟焦化装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"1#焦化富气压缩机KT1201\",\n" +
//                "      \"equipmentNo\": \"SHSHK1201\",\n" +
//                "      \"graphType\": 25,\n" +
//                "      \"equipmentName\": \"1#焦化富气压缩机KT1201\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200828357\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301762000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"c4652947ed4770938f3a800d9841ec78\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"涤纶部\",\n" +
//                "      \"factoryName\": \"涤纶部\",\n" +
//                "      \"factorySort\": 5,\n" +
//                "      \"unitId\": \"2#氧化装置\",\n" +
//                "      \"unitName\": \"2#氧化装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"TC203工艺空气压缩机\",\n" +
//                "      \"equipmentNo\": \"SHSHTC203\",\n" +
//                "      \"graphType\": 2,\n" +
//                "      \"equipmentName\": \"TC203工艺空气压缩机\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200772165\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301706000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"cb91e40b994b5e0dc6ab9dd60e32ea9d\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"芳烃部\",\n" +
//                "      \"factoryName\": \"芳烃部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"3#连续重整装置\",\n" +
//                "      \"unitName\": \"3#连续重整装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"K3201压缩机组\",\n" +
//                "      \"equipmentNo\": \"SHSHK3201\",\n" +
//                "      \"graphType\": 25,\n" +
//                "      \"equipmentName\": \"K3201压缩机组\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200700812\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301711000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"d0d87301f2eb73d784ee46d54dd6afcb\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"烯烃部\",\n" +
//                "      \"factoryName\": \"烯烃部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"2#烯烃装置\",\n" +
//                "      \"unitName\": \"2#乙烯装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"丙烯冷煤压缩机EGB-2501\",\n" +
//                "      \"equipmentNo\": \"EGB2501\",\n" +
//                "      \"graphType\": 25,\n" +
//                "      \"equipmentName\": \"丙烯冷媒压缩机EGB-2501\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200681833\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301813000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"d473973bf248dab68ceebf67609decbe\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"炼油部\",\n" +
//                "      \"factoryName\": \"炼油部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"2#重油催化裂化装置\",\n" +
//                "      \"unitName\": \"5#炼油2#催化裂化装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"炼油备风机K2101（AV63）\",\n" +
//                "      \"equipmentNo\": \"SHAHK2101\",\n" +
//                "      \"graphType\": 27,\n" +
//                "      \"equipmentName\": \"炼油备风机K2102(AV63)\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200843721\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301762000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"d74e270f9eadb526df9bdc29b459f4b2\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"热电部\",\n" +
//                "      \"factoryName\": \"热电部\",\n" +
//                "      \"factorySort\": 6,\n" +
//                "      \"unitId\": \"汽机装置\",\n" +
//                "      \"unitName\": \"汽机装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"6#发电机组\",\n" +
//                "      \"equipmentNo\": \"6FDJZ\",\n" +
//                "      \"graphType\": 11,\n" +
//                "      \"equipmentName\": \"6#发电机组\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200889872\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301805000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"dbad01c61c792edfc653e73f70618efc\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"炼油部\",\n" +
//                "      \"factoryName\": \"炼油部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"2#重油催化裂化装置\",\n" +
//                "      \"unitName\": \"5#炼油2#催化裂化装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"富气压缩机K2301\",\n" +
//                "      \"equipmentNo\": \"K2301\",\n" +
//                "      \"graphType\": 25,\n" +
//                "      \"equipmentName\": \"富气压缩机K2301\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200843711\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301762000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"e127c853292b273af188ab30b5c847ff\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"芳烃部\",\n" +
//                "      \"factoryName\": \"芳烃部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"2#连续再生重整装置\",\n" +
//                "      \"unitName\": \"2#连续重整装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"K201压缩机组\",\n" +
//                "      \"equipmentNo\": \"SHSHK201\",\n" +
//                "      \"graphType\": 25,\n" +
//                "      \"equipmentName\": \"K201压缩机组\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200700109\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301711000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"e432ad18f658c5cf8292142297afd177\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"化工部\",\n" +
//                "      \"factoryName\": \"化工部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"1#乙二醇装置\",\n" +
//                "      \"unitName\": \"1#环氧乙烷/乙二醇装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"循环气压缩机C-116\",\n" +
//                "      \"equipmentNo\": \"SHSHC116\",\n" +
//                "      \"graphType\": 65,\n" +
//                "      \"equipmentName\": \"循环气压缩机C-116\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200740743\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301752000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"e491e44c01a75145211fcbb07a9dc0d3\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"化工部\",\n" +
//                "      \"factoryName\": \"化工部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"1#乙二醇装置\",\n" +
//                "      \"unitName\": \"1#环氧乙烷/乙二醇装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"循环气压缩机C-115\",\n" +
//                "      \"equipmentNo\": \"SHSHC115\",\n" +
//                "      \"graphType\": 64,\n" +
//                "      \"equipmentName\": \"循环气压缩机C-115\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200740729\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301752000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"e8a1890d47d3a92d4507801c33df9e26\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"烯烃部\",\n" +
//                "      \"factoryName\": \"烯烃部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"2#烯烃装置\",\n" +
//                "      \"unitName\": \"2#乙烯装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"乙烯冷煤压缩机EGB-2601\",\n" +
//                "      \"equipmentNo\": \"EGB2601\",\n" +
//                "      \"graphType\": 25,\n" +
//                "      \"equipmentName\": \"乙烯冷媒压缩机EGB-2601\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200681834\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301813000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"ea50a326ee9a857a712a2353bd99d44c\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"芳烃部\",\n" +
//                "      \"factoryName\": \"芳烃部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"2#连续再生重整装置\",\n" +
//                "      \"unitName\": \"2#连续重整装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"K202-1压缩机组\",\n" +
//                "      \"equipmentNo\": \"K2021\",\n" +
//                "      \"graphType\": 25,\n" +
//                "      \"equipmentName\": \"K202-1压缩机组\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200700110\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301711000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"f0d600e56eb1308d7198b4892b18e392\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"芳烃部\",\n" +
//                "      \"factoryName\": \"芳烃部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"2#甲苯歧化异构化\",\n" +
//                "      \"unitName\": \"2#甲苯歧化异构化\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"K951压缩机组\",\n" +
//                "      \"equipmentNo\": \"SHSHK951\",\n" +
//                "      \"graphType\": 25,\n" +
//                "      \"equipmentName\": \"K951压缩机组\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"200700459\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301711000\n" +
//                "    },\n" +
//                "    {\n" +
//                "      \"equipmentUuid\": \"f9db790ee6da2961dfa70d6a4db63a67\",\n" +
//                "      \"alarmId\": 0,\n" +
//                "      \"alarmLevel\": -2,\n" +
//                "      \"alarmStatus\": 5,\n" +
//                "      \"alarmAlias\": \"断网\",\n" +
//                "      \"groupId\": \"中国石化\",\n" +
//                "      \"groupName\": \"中国石化\",\n" +
//                "      \"groupSort\": 0,\n" +
//                "      \"companyId\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companyName\": \"上海石油化工股份有限公司\",\n" +
//                "      \"companySort\": 0,\n" +
//                "      \"factoryId\": \"炼油部\",\n" +
//                "      \"factoryName\": \"炼油部\",\n" +
//                "      \"factorySort\": 0,\n" +
//                "      \"unitId\": \"2#柴油加氢装置\",\n" +
//                "      \"unitName\": \"3#炼油2#柴油加氢装置\",\n" +
//                "      \"unitSort\": 0,\n" +
//                "      \"equipmentId\": \"循环氢压缩机K/KT-4002\",\n" +
//                "      \"equipmentNo\": \"KT4002\",\n" +
//                "      \"graphType\": 25,\n" +
//                "      \"equipmentName\": \"循环氢压缩机K/KT-4002\",\n" +
//                "      \"equipmentSort\": 0,\n" +
//                "      \"equipmentType\": 0,\n" +
//                "      \"equipmentTypeName\": \"大机组\",\n" +
//                "      \"erpcode\": \"203821440\",\n" +
//                "      \"samplingNumber\": 16384,\n" +
//                "      \"samplingFreq\": 5120,\n" +
//                "      \"manufacturer\": \"创为实\",\n" +
//                "      \"rev\": -1,\n" +
//                "      \"nodeType\": 1,\n" +
//                "      \"nodeHost\": \"192.168.119.44\",\n" +
//                "      \"nodePort\": 17002,\n" +
//                "      \"updateTime\": 1665301762000\n" +
//                "    }\n" +
//                "  ]\n" +
//                "}");
//        JSONArray data = (JSONArray) parse.get("data");
//        for (int i = 0; i <data.size(); i++) {
//            JSONObject o = (JSONObject)data.get(i);
//            Object equipmentUuid = o.get("equipmentUuid");
//            System.out.println("\""+equipmentUuid.toString()+"\",");
//        }
//    }
}
